//  Copyright (c) 2013-2023 Snowplow Analytics Ltd. All rights reserved.
//
//  This program is licensed to you under the Apache License Version 2.0,
//  and you may not use this file except in compliance with the Apache License
//  Version 2.0. You may obtain a copy of the Apache License Version 2.0 at
//  http://www.apache.org/licenses/LICENSE-2.0.
//
//  Unless required by applicable law or agreed to in writing,
//  software distributed under the Apache License Version 2.0 is distributed on
//  an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
//  express or implied. See the Apache License Version 2.0 for the specific
//  language governing permissions and limitations there under.

import Foundation

/**
 Properties for the VisionOS window group entity.
 Entity schema: `iglu:com.apple.swiftui/window_group/jsonschema/1-0-0`
 */
@objc(SPWindowGroupEntity)
public class WindowGroupEntity: SelfDescribingJson {
    
    /// Randomly generated ID for the current window within the group. Generated by the tracker if not provided by the user.
    @objc
    public var id: UUID
    
    /// A localized string key to use for the window's title in system menus and in the window's title bar. Provide a title that describes the purpose of the window.
    @objc
    public var titleKey: String?
    
    /// A string that uniquely identifies the window group. Identifiers must be unique among the window groups in your app.
    @objc
    public var windowGroupId: String?
    
    /// A specification for the appearance and interaction of a window.
    public var windowStyle: WindowStyle?
    
    @objc
    override public var data: [String : Any] {
        get {
            var data: [String : Any] = [
                "id": id.uuidString
            ]
            if let titleKey = titleKey { data["title_key"] = titleKey }
            if let windowGroupId = windowGroupId { data["window_group_id"] = windowGroupId }
            if let windowStyle = windowStyle { data["window_style"] = windowStyle.value }
            return data
        }
        set {}
    }
    
    /// - Parameter id: Randomly generated ID for the current window within the group. Generated by the tracker if not provided by the user.
    /// - Parameter titleKey: A localized string key to use for the window's title in system menus and in the window's title bar.
    /// - Parameter windowGroupID: A string that uniquely identifies the window group.
    /// - Parameter windowStyle: A specification for the appearance and interaction of a window.
    public init(
        id: UUID = UUID(),
        titleKey: String? = nil,
        windowGroupID: String? = nil,
        windowStyle: WindowStyle? = nil
    ) {
        self.id = id
        self.titleKey = titleKey
        self.windowGroupId = windowGroupID
        self.windowStyle = windowStyle
        super.init(schema: visionOsWindowGroup, andData: [:])
    }
    
    /// - Parameter id: Randomly generated ID for the current window within the group. Generated by the tracker if not provided by the user.
    /// - Parameter titleKey: A localized string key to use for the window's title in system menus and in the window's title bar.
    /// - Parameter windowGroupID: A string that uniquely identifies the window group.
    @objc
    public init(
        id: UUID = UUID(),
        titleKey: String? = nil,
        windowGroupID: String? = nil
    ) {
        self.id = id
        self.titleKey = titleKey
        self.windowGroupId = windowGroupID
        super.init(schema: visionOsWindowGroup, andData: [:])
    }
    
    /// A specification for the appearance and interaction of a window.
    @objc
    public func windowStyle(_ windowStyle: WindowStyle) -> Self {
        self.windowStyle = windowStyle
        return self
    }
}
