var searchData=
[
  ['snowerror_2eh_0',['SNOWError.h',['../_internal_2_events_2_s_n_o_w_error_8h.html',1,'(Global Namespace)'],['../include_2_s_n_o_w_error_8h.html',1,'(Global Namespace)']]],
  ['snowerror_2em_1',['SNOWError.m',['../_s_n_o_w_error_8m.html',1,'']]],
  ['snowplow_2dumbrella_2dheader_2eh_2',['Snowplow-umbrella-header.h',['../_snowplow-umbrella-header_8h.html',1,'']]],
  ['snowreachability_2eh_3',['SNOWReachability.h',['../_s_n_o_w_reachability_8h.html',1,'']]],
  ['snowreachability_2em_4',['SNOWReachability.m',['../_s_n_o_w_reachability_8m.html',1,'']]],
  ['spbackground_2eh_5',['SPBackground.h',['../include_2_s_p_background_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_background_8h.html',1,'(Global Namespace)']]],
  ['spbackground_2em_6',['SPBackground.m',['../_s_p_background_8m.html',1,'']]],
  ['spconfiguration_2eh_7',['SPConfiguration.h',['../_internal_2_configurations_2_s_p_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_configuration_8h.html',1,'(Global Namespace)']]],
  ['spconfiguration_2em_8',['SPConfiguration.m',['../_s_p_configuration_8m.html',1,'']]],
  ['spconfigurationbundle_2eh_9',['SPConfigurationBundle.h',['../include_2_s_p_configuration_bundle_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_configuration_bundle_8h.html',1,'(Global Namespace)']]],
  ['spconfigurationbundle_2em_10',['SPConfigurationBundle.m',['../_s_p_configuration_bundle_8m.html',1,'']]],
  ['spconfigurationcache_2eh_11',['SPConfigurationCache.h',['../_s_p_configuration_cache_8h.html',1,'']]],
  ['spconfigurationcache_2em_12',['SPConfigurationCache.m',['../_s_p_configuration_cache_8m.html',1,'']]],
  ['spconfigurationfetcher_2eh_13',['SPConfigurationFetcher.h',['../_s_p_configuration_fetcher_8h.html',1,'']]],
  ['spconfigurationfetcher_2em_14',['SPConfigurationFetcher.m',['../_s_p_configuration_fetcher_8m.html',1,'']]],
  ['spconfigurationprovider_2eh_15',['SPConfigurationProvider.h',['../_s_p_configuration_provider_8h.html',1,'']]],
  ['spconfigurationprovider_2em_16',['SPConfigurationProvider.m',['../_s_p_configuration_provider_8m.html',1,'']]],
  ['spconfigurationstate_2eh_17',['SPConfigurationState.h',['../include_2_s_p_configuration_state_8h.html',1,'(Global Namespace)'],['../_internal_2_remote_configuration_2_s_p_configuration_state_8h.html',1,'(Global Namespace)']]],
  ['spconsentdocument_2eh_18',['SPConsentDocument.h',['../_internal_2_events_2_s_p_consent_document_8h.html',1,'(Global Namespace)'],['../include_2_s_p_consent_document_8h.html',1,'(Global Namespace)']]],
  ['spconsentdocument_2em_19',['SPConsentDocument.m',['../_s_p_consent_document_8m.html',1,'']]],
  ['spconsentgranted_2eh_20',['SPConsentGranted.h',['../include_2_s_p_consent_granted_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_consent_granted_8h.html',1,'(Global Namespace)']]],
  ['spconsentgranted_2em_21',['SPConsentGranted.m',['../_s_p_consent_granted_8m.html',1,'']]],
  ['spconsentwithdrawn_2eh_22',['SPConsentWithdrawn.h',['../include_2_s_p_consent_withdrawn_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_consent_withdrawn_8h.html',1,'(Global Namespace)']]],
  ['spconsentwithdrawn_2em_23',['SPConsentWithdrawn.m',['../_s_p_consent_withdrawn_8m.html',1,'']]],
  ['spcontroller_2eh_24',['SPController.h',['../_s_p_controller_8h.html',1,'']]],
  ['spcontroller_2em_25',['SPController.m',['../_s_p_controller_8m.html',1,'']]],
  ['spdatapersistence_2eh_26',['SPDataPersistence.h',['../_s_p_data_persistence_8h.html',1,'']]],
  ['spdatapersistence_2em_27',['SPDataPersistence.m',['../_s_p_data_persistence_8m.html',1,'']]],
  ['spdeeplinkentity_2eh_28',['SPDeepLinkEntity.h',['../_internal_2_entities_2_s_p_deep_link_entity_8h.html',1,'(Global Namespace)'],['../include_2_s_p_deep_link_entity_8h.html',1,'(Global Namespace)']]],
  ['spdeeplinkentity_2em_29',['SPDeepLinkEntity.m',['../_s_p_deep_link_entity_8m.html',1,'']]],
  ['spdeeplinkreceived_2eh_30',['SPDeepLinkReceived.h',['../include_2_s_p_deep_link_received_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_deep_link_received_8h.html',1,'(Global Namespace)']]],
  ['spdeeplinkreceived_2em_31',['SPDeepLinkReceived.m',['../_s_p_deep_link_received_8m.html',1,'']]],
  ['spdeeplinkstate_2eh_32',['SPDeepLinkState.h',['../_s_p_deep_link_state_8h.html',1,'']]],
  ['spdeeplinkstate_2em_33',['SPDeepLinkState.m',['../_s_p_deep_link_state_8m.html',1,'']]],
  ['spdeeplinkstatemachine_2eh_34',['SPDeepLinkStateMachine.h',['../_s_p_deep_link_state_machine_8h.html',1,'']]],
  ['spdeeplinkstatemachine_2em_35',['SPDeepLinkStateMachine.m',['../_s_p_deep_link_state_machine_8m.html',1,'']]],
  ['spdefaultnetworkconnection_2eh_36',['SPDefaultNetworkConnection.h',['../include_2_s_p_default_network_connection_8h.html',1,'(Global Namespace)'],['../_internal_2_network_connection_2_s_p_default_network_connection_8h.html',1,'(Global Namespace)']]],
  ['spdefaultnetworkconnection_2em_37',['SPDefaultNetworkConnection.m',['../_s_p_default_network_connection_8m.html',1,'']]],
  ['spdeviceinfomonitor_2eh_38',['SPDeviceInfoMonitor.h',['../_s_p_device_info_monitor_8h.html',1,'']]],
  ['spdeviceinfomonitor_2em_39',['SPDeviceInfoMonitor.m',['../_s_p_device_info_monitor_8m.html',1,'']]],
  ['spdeviceplatform_2eh_40',['SPDevicePlatform.h',['../_internal_2_subject_2_s_p_device_platform_8h.html',1,'(Global Namespace)'],['../include_2_s_p_device_platform_8h.html',1,'(Global Namespace)']]],
  ['spdeviceplatform_2em_41',['SPDevicePlatform.m',['../_s_p_device_platform_8m.html',1,'']]],
  ['specommerce_2eh_42',['SPEcommerce.h',['../_internal_2_events_2_s_p_ecommerce_8h.html',1,'(Global Namespace)'],['../include_2_s_p_ecommerce_8h.html',1,'(Global Namespace)']]],
  ['specommerce_2em_43',['SPEcommerce.m',['../_s_p_ecommerce_8m.html',1,'']]],
  ['specommerceitem_2eh_44',['SPEcommerceItem.h',['../_internal_2_events_2_s_p_ecommerce_item_8h.html',1,'(Global Namespace)'],['../include_2_s_p_ecommerce_item_8h.html',1,'(Global Namespace)']]],
  ['specommerceitem_2em_45',['SPEcommerceItem.m',['../_s_p_ecommerce_item_8m.html',1,'']]],
  ['spemitter_2eh_46',['SPEmitter.h',['../_s_p_emitter_8h.html',1,'']]],
  ['spemitter_2em_47',['SPEmitter.m',['../_s_p_emitter_8m.html',1,'']]],
  ['spemitterconfiguration_2eh_48',['SPEmitterConfiguration.h',['../_internal_2_configurations_2_s_p_emitter_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_emitter_configuration_8h.html',1,'(Global Namespace)']]],
  ['spemitterconfiguration_2em_49',['SPEmitterConfiguration.m',['../_s_p_emitter_configuration_8m.html',1,'']]],
  ['spemitterconfigurationupdate_2eh_50',['SPEmitterConfigurationUpdate.h',['../_s_p_emitter_configuration_update_8h.html',1,'']]],
  ['spemitterconfigurationupdate_2em_51',['SPEmitterConfigurationUpdate.m',['../_s_p_emitter_configuration_update_8m.html',1,'']]],
  ['spemittercontroller_2eh_52',['SPEmitterController.h',['../include_2_s_p_emitter_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_emitter_controller_8h.html',1,'(Global Namespace)']]],
  ['spemittercontrollerimpl_2eh_53',['SPEmitterControllerImpl.h',['../_s_p_emitter_controller_impl_8h.html',1,'']]],
  ['spemittercontrollerimpl_2em_54',['SPEmitterControllerImpl.m',['../_s_p_emitter_controller_impl_8m.html',1,'']]],
  ['spemitterevent_2eh_55',['SPEmitterEvent.h',['../_internal_2_emitter_2_s_p_emitter_event_8h.html',1,'(Global Namespace)'],['../include_2_s_p_emitter_event_8h.html',1,'(Global Namespace)']]],
  ['spemitterevent_2em_56',['SPEmitterEvent.m',['../_s_p_emitter_event_8m.html',1,'']]],
  ['spemittereventprocessing_2eh_57',['SPEmitterEventProcessing.h',['../_s_p_emitter_event_processing_8h.html',1,'']]],
  ['spevent_2eh_58',['SPEvent.h',['../_s_p_event_8h.html',1,'']]],
  ['speventbase_2eh_59',['SPEventBase.h',['../_internal_2_events_2_s_p_event_base_8h.html',1,'(Global Namespace)'],['../include_2_s_p_event_base_8h.html',1,'(Global Namespace)']]],
  ['speventbase_2em_60',['SPEventBase.m',['../_s_p_event_base_8m.html',1,'']]],
  ['speventstore_2eh_61',['SPEventStore.h',['../_internal_2_storage_2_s_p_event_store_8h.html',1,'(Global Namespace)'],['../include_2_s_p_event_store_8h.html',1,'(Global Namespace)']]],
  ['spfetchedconfigurationbundle_2eh_62',['SPFetchedConfigurationBundle.h',['../_s_p_fetched_configuration_bundle_8h.html',1,'']]],
  ['spfetchedconfigurationbundle_2em_63',['SPFetchedConfigurationBundle.m',['../_s_p_fetched_configuration_bundle_8m.html',1,'']]],
  ['spforeground_2eh_64',['SPForeground.h',['../include_2_s_p_foreground_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_foreground_8h.html',1,'(Global Namespace)']]],
  ['spforeground_2em_65',['SPForeground.m',['../_s_p_foreground_8m.html',1,'']]],
  ['spgdprconfiguration_2eh_66',['SPGDPRConfiguration.h',['../include_2_s_p_g_d_p_r_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_g_d_p_r_configuration_8h.html',1,'(Global Namespace)']]],
  ['spgdprconfiguration_2em_67',['SPGDPRConfiguration.m',['../_s_p_g_d_p_r_configuration_8m.html',1,'']]],
  ['spgdprconfigurationupdate_2eh_68',['SPGDPRConfigurationUpdate.h',['../_s_p_g_d_p_r_configuration_update_8h.html',1,'']]],
  ['spgdprconfigurationupdate_2em_69',['SPGDPRConfigurationUpdate.m',['../_s_p_g_d_p_r_configuration_update_8m.html',1,'']]],
  ['spgdprcontext_2eh_70',['SPGdprContext.h',['../_s_p_gdpr_context_8h.html',1,'']]],
  ['spgdprcontext_2em_71',['SPGdprContext.m',['../_s_p_gdpr_context_8m.html',1,'']]],
  ['spgdprcontroller_2eh_72',['SPGDPRController.h',['../_internal_2_g_d_p_r_2_s_p_g_d_p_r_controller_8h.html',1,'(Global Namespace)'],['../include_2_s_p_g_d_p_r_controller_8h.html',1,'(Global Namespace)']]],
  ['spgdprcontrollerimpl_2eh_73',['SPGDPRControllerImpl.h',['../_s_p_g_d_p_r_controller_impl_8h.html',1,'']]],
  ['spgdprcontrollerimpl_2em_74',['SPGDPRControllerImpl.m',['../_s_p_g_d_p_r_controller_impl_8m.html',1,'']]],
  ['spglobalcontext_2eh_75',['SPGlobalContext.h',['../_internal_2_global_contexts_2_s_p_global_context_8h.html',1,'(Global Namespace)'],['../include_2_s_p_global_context_8h.html',1,'(Global Namespace)']]],
  ['spglobalcontext_2em_76',['SPGlobalContext.m',['../_s_p_global_context_8m.html',1,'']]],
  ['spglobalcontextsconfiguration_2eh_77',['SPGlobalContextsConfiguration.h',['../_internal_2_configurations_2_s_p_global_contexts_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_global_contexts_configuration_8h.html',1,'(Global Namespace)']]],
  ['spglobalcontextsconfiguration_2em_78',['SPGlobalContextsConfiguration.m',['../_s_p_global_contexts_configuration_8m.html',1,'']]],
  ['spglobalcontextscontroller_2eh_79',['SPGlobalContextsController.h',['../_internal_2_global_contexts_2_s_p_global_contexts_controller_8h.html',1,'(Global Namespace)'],['../include_2_s_p_global_contexts_controller_8h.html',1,'(Global Namespace)']]],
  ['spglobalcontextscontrollerimpl_2eh_80',['SPGlobalContextsControllerImpl.h',['../_s_p_global_contexts_controller_impl_8h.html',1,'']]],
  ['spglobalcontextscontrollerimpl_2em_81',['SPGlobalContextsControllerImpl.m',['../_s_p_global_contexts_controller_impl_8m.html',1,'']]],
  ['spinstalltracker_2eh_82',['SPInstallTracker.h',['../_s_p_install_tracker_8h.html',1,'']]],
  ['spinstalltracker_2em_83',['SPInstallTracker.m',['../_s_p_install_tracker_8m.html',1,'']]],
  ['spjsonserialization_2eh_84',['SPJSONSerialization.h',['../_s_p_j_s_o_n_serialization_8h.html',1,'']]],
  ['spjsonserialization_2em_85',['SPJSONSerialization.m',['../_s_p_j_s_o_n_serialization_8m.html',1,'']]],
  ['splifecycleentity_2eh_86',['SPLifecycleEntity.h',['../include_2_s_p_lifecycle_entity_8h.html',1,'(Global Namespace)'],['../_internal_2_entities_2_s_p_lifecycle_entity_8h.html',1,'(Global Namespace)']]],
  ['splifecycleentity_2em_87',['SPLifecycleEntity.m',['../_s_p_lifecycle_entity_8m.html',1,'']]],
  ['splifecyclestate_2eh_88',['SPLifecycleState.h',['../_s_p_lifecycle_state_8h.html',1,'']]],
  ['splifecyclestate_2em_89',['SPLifecycleState.m',['../_s_p_lifecycle_state_8m.html',1,'']]],
  ['splifecyclestatemachine_2eh_90',['SPLifecycleStateMachine.h',['../_s_p_lifecycle_state_machine_8h.html',1,'']]],
  ['splifecyclestatemachine_2em_91',['SPLifecycleStateMachine.m',['../_s_p_lifecycle_state_machine_8m.html',1,'']]],
  ['splogger_2eh_92',['SPLogger.h',['../_s_p_logger_8h.html',1,'']]],
  ['splogger_2em_93',['SPLogger.m',['../_s_p_logger_8m.html',1,'']]],
  ['sploggerdelegate_2eh_94',['SPLoggerDelegate.h',['../_internal_2_logger_2_s_p_logger_delegate_8h.html',1,'(Global Namespace)'],['../include_2_s_p_logger_delegate_8h.html',1,'(Global Namespace)']]],
  ['spmemoryeventstore_2eh_95',['SPMemoryEventStore.h',['../_internal_2_storage_2_s_p_memory_event_store_8h.html',1,'(Global Namespace)'],['../include_2_s_p_memory_event_store_8h.html',1,'(Global Namespace)']]],
  ['spmemoryeventstore_2em_96',['SPMemoryEventStore.m',['../_s_p_memory_event_store_8m.html',1,'']]],
  ['spmessagenotification_2eh_97',['SPMessageNotification.h',['../_internal_2_events_2_s_p_message_notification_8h.html',1,'(Global Namespace)'],['../include_2_s_p_message_notification_8h.html',1,'(Global Namespace)']]],
  ['spmessagenotification_2em_98',['SPMessageNotification.m',['../_s_p_message_notification_8m.html',1,'']]],
  ['spmessagenotificationattachment_2eh_99',['SPMessageNotificationAttachment.h',['../_internal_2_events_2_s_p_message_notification_attachment_8h.html',1,'(Global Namespace)'],['../include_2_s_p_message_notification_attachment_8h.html',1,'(Global Namespace)']]],
  ['spmessagenotificationattachment_2em_100',['SPMessageNotificationAttachment.m',['../_s_p_message_notification_attachment_8m.html',1,'']]],
  ['spnetworkconfiguration_2eh_101',['SPNetworkConfiguration.h',['../include_2_s_p_network_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_network_configuration_8h.html',1,'(Global Namespace)']]],
  ['spnetworkconfiguration_2em_102',['SPNetworkConfiguration.m',['../_s_p_network_configuration_8m.html',1,'']]],
  ['spnetworkconfigurationupdate_2eh_103',['SPNetworkConfigurationUpdate.h',['../_s_p_network_configuration_update_8h.html',1,'']]],
  ['spnetworkconfigurationupdate_2em_104',['SPNetworkConfigurationUpdate.m',['../_s_p_network_configuration_update_8m.html',1,'']]],
  ['spnetworkconnection_2eh_105',['SPNetworkConnection.h',['../_internal_2_network_connection_2_s_p_network_connection_8h.html',1,'(Global Namespace)'],['../include_2_s_p_network_connection_8h.html',1,'(Global Namespace)']]],
  ['spnetworkcontroller_2eh_106',['SPNetworkController.h',['../include_2_s_p_network_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_network_connection_2_s_p_network_controller_8h.html',1,'(Global Namespace)']]],
  ['spnetworkcontrollerimpl_2eh_107',['SPNetworkControllerImpl.h',['../_s_p_network_controller_impl_8h.html',1,'']]],
  ['spnetworkcontrollerimpl_2em_108',['SPNetworkControllerImpl.m',['../_s_p_network_controller_impl_8m.html',1,'']]],
  ['sppageview_2eh_109',['SPPageView.h',['../include_2_s_p_page_view_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_page_view_8h.html',1,'(Global Namespace)']]],
  ['sppageview_2em_110',['SPPageView.m',['../_s_p_page_view_8m.html',1,'']]],
  ['sppayload_2eh_111',['SPPayload.h',['../_internal_2_payload_2_s_p_payload_8h.html',1,'(Global Namespace)'],['../include_2_s_p_payload_8h.html',1,'(Global Namespace)']]],
  ['sppayload_2em_112',['SPPayload.m',['../_s_p_payload_8m.html',1,'']]],
  ['spplatformcontext_2eh_113',['SPPlatformContext.h',['../_s_p_platform_context_8h.html',1,'']]],
  ['spplatformcontext_2em_114',['SPPlatformContext.m',['../_s_p_platform_context_8m.html',1,'']]],
  ['sppushnotification_2eh_115',['SPPushNotification.h',['../_internal_2_events_2_s_p_push_notification_8h.html',1,'(Global Namespace)'],['../include_2_s_p_push_notification_8h.html',1,'(Global Namespace)']]],
  ['sppushnotification_2em_116',['SPPushNotification.m',['../_s_p_push_notification_8m.html',1,'']]],
  ['spremoteconfiguration_2eh_117',['SPRemoteConfiguration.h',['../include_2_s_p_remote_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_remote_configuration_8h.html',1,'(Global Namespace)']]],
  ['spremoteconfiguration_2em_118',['SPRemoteConfiguration.m',['../_s_p_remote_configuration_8m.html',1,'']]],
  ['sprequest_2eh_119',['SPRequest.h',['../_internal_2_emitter_2_s_p_request_8h.html',1,'(Global Namespace)'],['../include_2_s_p_request_8h.html',1,'(Global Namespace)']]],
  ['sprequest_2em_120',['SPRequest.m',['../_s_p_request_8m.html',1,'']]],
  ['sprequestcallback_2eh_121',['SPRequestCallback.h',['../_internal_2_emitter_2_s_p_request_callback_8h.html',1,'(Global Namespace)'],['../include_2_s_p_request_callback_8h.html',1,'(Global Namespace)']]],
  ['sprequestresult_2eh_122',['SPRequestResult.h',['../_internal_2_emitter_2_s_p_request_result_8h.html',1,'(Global Namespace)'],['../include_2_s_p_request_result_8h.html',1,'(Global Namespace)']]],
  ['sprequestresult_2em_123',['SPRequestResult.m',['../_s_p_request_result_8m.html',1,'']]],
  ['spschemarule_2eh_124',['SPSchemaRule.h',['../include_2_s_p_schema_rule_8h.html',1,'(Global Namespace)'],['../_internal_2_global_contexts_2_s_p_schema_rule_8h.html',1,'(Global Namespace)']]],
  ['spschemarule_2em_125',['SPSchemaRule.m',['../_s_p_schema_rule_8m.html',1,'']]],
  ['spschemaruleset_2eh_126',['SPSchemaRuleset.h',['../include_2_s_p_schema_ruleset_8h.html',1,'(Global Namespace)'],['../_internal_2_global_contexts_2_s_p_schema_ruleset_8h.html',1,'(Global Namespace)']]],
  ['spschemaruleset_2em_127',['SPSchemaRuleset.m',['../_s_p_schema_ruleset_8m.html',1,'']]],
  ['spscreenstate_2eh_128',['SPScreenState.h',['../_s_p_screen_state_8h.html',1,'']]],
  ['spscreenstate_2em_129',['SPScreenState.m',['../_s_p_screen_state_8m.html',1,'']]],
  ['spscreenstatemachine_2eh_130',['SPScreenStateMachine.h',['../_s_p_screen_state_machine_8h.html',1,'']]],
  ['spscreenstatemachine_2em_131',['SPScreenStateMachine.m',['../_s_p_screen_state_machine_8m.html',1,'']]],
  ['spscreenview_2eh_132',['SPScreenView.h',['../include_2_s_p_screen_view_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_screen_view_8h.html',1,'(Global Namespace)']]],
  ['spscreenview_2em_133',['SPScreenView.m',['../_s_p_screen_view_8m.html',1,'']]],
  ['spselfdescribing_2eh_134',['SPSelfDescribing.h',['../_internal_2_events_2_s_p_self_describing_8h.html',1,'(Global Namespace)'],['../include_2_s_p_self_describing_8h.html',1,'(Global Namespace)']]],
  ['spselfdescribing_2em_135',['SPSelfDescribing.m',['../_s_p_self_describing_8m.html',1,'']]],
  ['spselfdescribingjson_2eh_136',['SPSelfDescribingJson.h',['../include_2_s_p_self_describing_json_8h.html',1,'(Global Namespace)'],['../_internal_2_payload_2_s_p_self_describing_json_8h.html',1,'(Global Namespace)']]],
  ['spselfdescribingjson_2em_137',['SPSelfDescribingJson.m',['../_s_p_self_describing_json_8m.html',1,'']]],
  ['spserviceprovider_2eh_138',['SPServiceProvider.h',['../_s_p_service_provider_8h.html',1,'']]],
  ['spserviceprovider_2em_139',['SPServiceProvider.m',['../_s_p_service_provider_8m.html',1,'']]],
  ['spserviceproviderprotocol_2eh_140',['SPServiceProviderProtocol.h',['../_s_p_service_provider_protocol_8h.html',1,'']]],
  ['spsession_2eh_141',['SPSession.h',['../_s_p_session_8h.html',1,'']]],
  ['spsession_2em_142',['SPSession.m',['../_s_p_session_8m.html',1,'']]],
  ['spsessionconfiguration_2eh_143',['SPSessionConfiguration.h',['../_internal_2_configurations_2_s_p_session_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_session_configuration_8h.html',1,'(Global Namespace)']]],
  ['spsessionconfiguration_2em_144',['SPSessionConfiguration.m',['../_s_p_session_configuration_8m.html',1,'']]],
  ['spsessionconfigurationupdate_2eh_145',['SPSessionConfigurationUpdate.h',['../_s_p_session_configuration_update_8h.html',1,'']]],
  ['spsessionconfigurationupdate_2em_146',['SPSessionConfigurationUpdate.m',['../_s_p_session_configuration_update_8m.html',1,'']]],
  ['spsessioncontroller_2eh_147',['SPSessionController.h',['../_internal_2_session_2_s_p_session_controller_8h.html',1,'(Global Namespace)'],['../include_2_s_p_session_controller_8h.html',1,'(Global Namespace)']]],
  ['spsessioncontrollerimpl_2eh_148',['SPSessionControllerImpl.h',['../_s_p_session_controller_impl_8h.html',1,'']]],
  ['spsessioncontrollerimpl_2em_149',['SPSessionControllerImpl.m',['../_s_p_session_controller_impl_8m.html',1,'']]],
  ['spsessionstate_2eh_150',['SPSessionState.h',['../_internal_2_session_2_s_p_session_state_8h.html',1,'(Global Namespace)'],['../include_2_s_p_session_state_8h.html',1,'(Global Namespace)']]],
  ['spsessionstate_2em_151',['SPSessionState.m',['../_s_p_session_state_8m.html',1,'']]],
  ['spsnowplow_2eh_152',['SPSnowplow.h',['../include_2_s_p_snowplow_8h.html',1,'(Global Namespace)'],['../_internal_2_s_p_snowplow_8h.html',1,'(Global Namespace)']]],
  ['spsnowplow_2em_153',['SPSnowplow.m',['../_s_p_snowplow_8m.html',1,'']]],
  ['spsqliteeventstore_2eh_154',['SPSQLiteEventStore.h',['../_internal_2_storage_2_s_p_s_q_lite_event_store_8h.html',1,'(Global Namespace)'],['../include_2_s_p_s_q_lite_event_store_8h.html',1,'(Global Namespace)']]],
  ['spsqliteeventstore_2em_155',['SPSQLiteEventStore.m',['../_s_p_s_q_lite_event_store_8m.html',1,'']]],
  ['spstate_2eh_156',['SPState.h',['../include_2_s_p_state_8h.html',1,'(Global Namespace)'],['../_internal_2_tracker_2_s_p_state_8h.html',1,'(Global Namespace)']]],
  ['spstatefuture_2eh_157',['SPStateFuture.h',['../_s_p_state_future_8h.html',1,'']]],
  ['spstatefuture_2em_158',['SPStateFuture.m',['../_s_p_state_future_8m.html',1,'']]],
  ['spstatemachineprotocol_2eh_159',['SPStateMachineProtocol.h',['../_s_p_state_machine_protocol_8h.html',1,'']]],
  ['spstatemanager_2eh_160',['SPStateManager.h',['../_s_p_state_manager_8h.html',1,'']]],
  ['spstatemanager_2em_161',['SPStateManager.m',['../_s_p_state_manager_8m.html',1,'']]],
  ['spstructured_2eh_162',['SPStructured.h',['../_internal_2_events_2_s_p_structured_8h.html',1,'(Global Namespace)'],['../include_2_s_p_structured_8h.html',1,'(Global Namespace)']]],
  ['spstructured_2em_163',['SPStructured.m',['../_s_p_structured_8m.html',1,'']]],
  ['spsubject_2eh_164',['SPSubject.h',['../_s_p_subject_8h.html',1,'']]],
  ['spsubject_2em_165',['SPSubject.m',['../_s_p_subject_8m.html',1,'']]],
  ['spsubjectconfiguration_2eh_166',['SPSubjectConfiguration.h',['../_internal_2_configurations_2_s_p_subject_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_subject_configuration_8h.html',1,'(Global Namespace)']]],
  ['spsubjectconfiguration_2em_167',['SPSubjectConfiguration.m',['../_s_p_subject_configuration_8m.html',1,'']]],
  ['spsubjectconfigurationupdate_2eh_168',['SPSubjectConfigurationUpdate.h',['../_s_p_subject_configuration_update_8h.html',1,'']]],
  ['spsubjectconfigurationupdate_2em_169',['SPSubjectConfigurationUpdate.m',['../_s_p_subject_configuration_update_8m.html',1,'']]],
  ['spsubjectcontroller_2eh_170',['SPSubjectController.h',['../include_2_s_p_subject_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_subject_2_s_p_subject_controller_8h.html',1,'(Global Namespace)']]],
  ['spsubjectcontrollerimpl_2eh_171',['SPSubjectControllerImpl.h',['../_s_p_subject_controller_impl_8h.html',1,'']]],
  ['spsubjectcontrollerimpl_2em_172',['SPSubjectControllerImpl.m',['../_s_p_subject_controller_impl_8m.html',1,'']]],
  ['sptiming_2eh_173',['SPTiming.h',['../include_2_s_p_timing_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_timing_8h.html',1,'(Global Namespace)']]],
  ['sptiming_2em_174',['SPTiming.m',['../_s_p_timing_8m.html',1,'']]],
  ['sptracker_2eh_175',['SPTracker.h',['../_s_p_tracker_8h.html',1,'']]],
  ['sptracker_2em_176',['SPTracker.m',['../_s_p_tracker_8m.html',1,'']]],
  ['sptrackerconfiguration_2eh_177',['SPTrackerConfiguration.h',['../include_2_s_p_tracker_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_tracker_configuration_8h.html',1,'(Global Namespace)']]],
  ['sptrackerconfiguration_2em_178',['SPTrackerConfiguration.m',['../_s_p_tracker_configuration_8m.html',1,'']]],
  ['sptrackerconfigurationupdate_2eh_179',['SPTrackerConfigurationUpdate.h',['../_s_p_tracker_configuration_update_8h.html',1,'']]],
  ['sptrackerconfigurationupdate_2em_180',['SPTrackerConfigurationUpdate.m',['../_s_p_tracker_configuration_update_8m.html',1,'']]],
  ['sptrackerconstants_2eh_181',['SPTrackerConstants.h',['../include_2_s_p_tracker_constants_8h.html',1,'(Global Namespace)'],['../_internal_2_s_p_tracker_constants_8h.html',1,'(Global Namespace)']]],
  ['sptrackerconstants_2em_182',['SPTrackerConstants.m',['../_s_p_tracker_constants_8m.html',1,'']]],
  ['sptrackercontroller_2eh_183',['SPTrackerController.h',['../_internal_2_tracker_2_s_p_tracker_controller_8h.html',1,'(Global Namespace)'],['../include_2_s_p_tracker_controller_8h.html',1,'(Global Namespace)']]],
  ['sptrackercontrollerimpl_2eh_184',['SPTrackerControllerImpl.h',['../_s_p_tracker_controller_impl_8h.html',1,'']]],
  ['sptrackercontrollerimpl_2em_185',['SPTrackerControllerImpl.m',['../_s_p_tracker_controller_impl_8m.html',1,'']]],
  ['sptrackererror_2eh_186',['SPTrackerError.h',['../_s_p_tracker_error_8h.html',1,'']]],
  ['sptrackererror_2em_187',['SPTrackerError.m',['../_s_p_tracker_error_8m.html',1,'']]],
  ['sptrackerevent_2eh_188',['SPTrackerEvent.h',['../_s_p_tracker_event_8h.html',1,'']]],
  ['sptrackerevent_2em_189',['SPTrackerEvent.m',['../_s_p_tracker_event_8m.html',1,'']]],
  ['sptrackerstate_2eh_190',['SPTrackerState.h',['../_s_p_tracker_state_8h.html',1,'']]],
  ['sptrackerstate_2em_191',['SPTrackerState.m',['../_s_p_tracker_state_8m.html',1,'']]],
  ['sptrackerstatesnapshot_2eh_192',['SPTrackerStateSnapshot.h',['../include_2_s_p_tracker_state_snapshot_8h.html',1,'(Global Namespace)'],['../_internal_2_tracker_2_s_p_tracker_state_snapshot_8h.html',1,'(Global Namespace)']]],
  ['sputilities_2eh_193',['SPUtilities.h',['../_s_p_utilities_8h.html',1,'']]],
  ['sputilities_2em_194',['SPUtilities.m',['../_s_p_utilities_8m.html',1,'']]],
  ['spweaktimertarget_2eh_195',['SPWeakTimerTarget.h',['../_s_p_weak_timer_target_8h.html',1,'']]],
  ['spweaktimertarget_2em_196',['SPWeakTimerTarget.m',['../_s_p_weak_timer_target_8m.html',1,'']]],
  ['spwebviewmessagehandler_2eh_197',['SPWebViewMessageHandler.h',['../_s_p_web_view_message_handler_8h.html',1,'']]],
  ['spwebviewmessagehandler_2em_198',['SPWebViewMessageHandler.m',['../_s_p_web_view_message_handler_8m.html',1,'']]]
];
