var searchData=
[
  ['snowerror_2eh_1166',['SNOWError.h',['../_internal_2_events_2_s_n_o_w_error_8h.html',1,'(Global Namespace)'],['../include_2_s_n_o_w_error_8h.html',1,'(Global Namespace)']]],
  ['snowerror_2em_1167',['SNOWError.m',['../_s_n_o_w_error_8m.html',1,'']]],
  ['snowplow_2dumbrella_2dheader_2eh_1168',['Snowplow-umbrella-header.h',['../_snowplow-umbrella-header_8h.html',1,'']]],
  ['snowreachability_2eh_1169',['SNOWReachability.h',['../_s_n_o_w_reachability_8h.html',1,'']]],
  ['snowreachability_2em_1170',['SNOWReachability.m',['../_s_n_o_w_reachability_8m.html',1,'']]],
  ['spbackground_2eh_1171',['SPBackground.h',['../include_2_s_p_background_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_background_8h.html',1,'(Global Namespace)']]],
  ['spbackground_2em_1172',['SPBackground.m',['../_s_p_background_8m.html',1,'']]],
  ['spconfiguration_2eh_1173',['SPConfiguration.h',['../_internal_2_configurations_2_s_p_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_configuration_8h.html',1,'(Global Namespace)']]],
  ['spconfiguration_2em_1174',['SPConfiguration.m',['../_s_p_configuration_8m.html',1,'']]],
  ['spconsentdocument_2eh_1175',['SPConsentDocument.h',['../include_2_s_p_consent_document_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_consent_document_8h.html',1,'(Global Namespace)']]],
  ['spconsentdocument_2em_1176',['SPConsentDocument.m',['../_s_p_consent_document_8m.html',1,'']]],
  ['spconsentgranted_2eh_1177',['SPConsentGranted.h',['../include_2_s_p_consent_granted_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_consent_granted_8h.html',1,'(Global Namespace)']]],
  ['spconsentgranted_2em_1178',['SPConsentGranted.m',['../_s_p_consent_granted_8m.html',1,'']]],
  ['spconsentwithdrawn_2eh_1179',['SPConsentWithdrawn.h',['../_internal_2_events_2_s_p_consent_withdrawn_8h.html',1,'(Global Namespace)'],['../include_2_s_p_consent_withdrawn_8h.html',1,'(Global Namespace)']]],
  ['spconsentwithdrawn_2em_1180',['SPConsentWithdrawn.m',['../_s_p_consent_withdrawn_8m.html',1,'']]],
  ['spdefaultnetworkconnection_2eh_1181',['SPDefaultNetworkConnection.h',['../include_2_s_p_default_network_connection_8h.html',1,'(Global Namespace)'],['../_internal_2_network_connection_2_s_p_default_network_connection_8h.html',1,'(Global Namespace)']]],
  ['spdefaultnetworkconnection_2em_1182',['SPDefaultNetworkConnection.m',['../_s_p_default_network_connection_8m.html',1,'']]],
  ['spdeviceplatform_2eh_1183',['SPDevicePlatform.h',['../include_2_s_p_device_platform_8h.html',1,'(Global Namespace)'],['../_internal_2_subject_2_s_p_device_platform_8h.html',1,'(Global Namespace)']]],
  ['spdeviceplatform_2em_1184',['SPDevicePlatform.m',['../_s_p_device_platform_8m.html',1,'']]],
  ['specommerce_2eh_1185',['SPEcommerce.h',['../include_2_s_p_ecommerce_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_ecommerce_8h.html',1,'(Global Namespace)']]],
  ['specommerce_2em_1186',['SPEcommerce.m',['../_s_p_ecommerce_8m.html',1,'']]],
  ['specommerceitem_2eh_1187',['SPEcommerceItem.h',['../_internal_2_events_2_s_p_ecommerce_item_8h.html',1,'(Global Namespace)'],['../include_2_s_p_ecommerce_item_8h.html',1,'(Global Namespace)']]],
  ['specommerceitem_2em_1188',['SPEcommerceItem.m',['../_s_p_ecommerce_item_8m.html',1,'']]],
  ['spemitter_2eh_1189',['SPEmitter.h',['../include_2_s_p_emitter_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_emitter_8h.html',1,'(Global Namespace)']]],
  ['spemitter_2em_1190',['SPEmitter.m',['../_s_p_emitter_8m.html',1,'']]],
  ['spemitterconfiguration_2eh_1191',['SPEmitterConfiguration.h',['../include_2_s_p_emitter_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_emitter_configuration_8h.html',1,'(Global Namespace)']]],
  ['spemitterconfiguration_2em_1192',['SPEmitterConfiguration.m',['../_s_p_emitter_configuration_8m.html',1,'']]],
  ['spemittercontroller_2eh_1193',['SPEmitterController.h',['../include_2_s_p_emitter_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_emitter_controller_8h.html',1,'(Global Namespace)']]],
  ['spemittercontrollerimpl_2eh_1194',['SPEmitterControllerImpl.h',['../_s_p_emitter_controller_impl_8h.html',1,'']]],
  ['spemittercontrollerimpl_2em_1195',['SPEmitterControllerImpl.m',['../_s_p_emitter_controller_impl_8m.html',1,'']]],
  ['spemitterevent_2eh_1196',['SPEmitterEvent.h',['../include_2_s_p_emitter_event_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_emitter_event_8h.html',1,'(Global Namespace)']]],
  ['spemitterevent_2em_1197',['SPEmitterEvent.m',['../_s_p_emitter_event_8m.html',1,'']]],
  ['spemittereventprocessing_2eh_1198',['SPEmitterEventProcessing.h',['../include_2_s_p_emitter_event_processing_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_emitter_event_processing_8h.html',1,'(Global Namespace)']]],
  ['spevent_2eh_1199',['SPEvent.h',['../_s_p_event_8h.html',1,'']]],
  ['speventbase_2eh_1200',['SPEventBase.h',['../_internal_2_events_2_s_p_event_base_8h.html',1,'(Global Namespace)'],['../include_2_s_p_event_base_8h.html',1,'(Global Namespace)']]],
  ['speventbase_2em_1201',['SPEventBase.m',['../_s_p_event_base_8m.html',1,'']]],
  ['speventstore_2eh_1202',['SPEventStore.h',['../_internal_2_storage_2_s_p_event_store_8h.html',1,'(Global Namespace)'],['../include_2_s_p_event_store_8h.html',1,'(Global Namespace)']]],
  ['spforeground_2eh_1203',['SPForeground.h',['../_internal_2_events_2_s_p_foreground_8h.html',1,'(Global Namespace)'],['../include_2_s_p_foreground_8h.html',1,'(Global Namespace)']]],
  ['spforeground_2em_1204',['SPForeground.m',['../_s_p_foreground_8m.html',1,'']]],
  ['spgdprconfiguration_2eh_1205',['SPGDPRConfiguration.h',['../_internal_2_configurations_2_s_p_g_d_p_r_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_g_d_p_r_configuration_8h.html',1,'(Global Namespace)']]],
  ['spgdprconfiguration_2em_1206',['SPGDPRConfiguration.m',['../_s_p_g_d_p_r_configuration_8m.html',1,'']]],
  ['spgdprcontext_2eh_1207',['SPGdprContext.h',['../_internal_2_g_d_p_r_2_s_p_gdpr_context_8h.html',1,'(Global Namespace)'],['../include_2_s_p_gdpr_context_8h.html',1,'(Global Namespace)']]],
  ['spgdprcontext_2em_1208',['SPGdprContext.m',['../_s_p_gdpr_context_8m.html',1,'']]],
  ['spgdprcontroller_2eh_1209',['SPGDPRController.h',['../include_2_s_p_g_d_p_r_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_g_d_p_r_2_s_p_g_d_p_r_controller_8h.html',1,'(Global Namespace)']]],
  ['spgdprcontrollerimpl_2eh_1210',['SPGDPRControllerImpl.h',['../_s_p_g_d_p_r_controller_impl_8h.html',1,'']]],
  ['spgdprcontrollerimpl_2em_1211',['SPGDPRControllerImpl.m',['../_s_p_g_d_p_r_controller_impl_8m.html',1,'']]],
  ['spglobalcontext_2eh_1212',['SPGlobalContext.h',['../_internal_2_global_contexts_2_s_p_global_context_8h.html',1,'(Global Namespace)'],['../include_2_s_p_global_context_8h.html',1,'(Global Namespace)']]],
  ['spglobalcontext_2em_1213',['SPGlobalContext.m',['../_s_p_global_context_8m.html',1,'']]],
  ['spglobalcontextsconfiguration_2eh_1214',['SPGlobalContextsConfiguration.h',['../include_2_s_p_global_contexts_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_global_contexts_configuration_8h.html',1,'(Global Namespace)']]],
  ['spglobalcontextsconfiguration_2em_1215',['SPGlobalContextsConfiguration.m',['../_s_p_global_contexts_configuration_8m.html',1,'']]],
  ['spglobalcontextscontroller_2eh_1216',['SPGlobalContextsController.h',['../_internal_2_global_contexts_2_s_p_global_contexts_controller_8h.html',1,'(Global Namespace)'],['../include_2_s_p_global_contexts_controller_8h.html',1,'(Global Namespace)']]],
  ['spglobalcontextscontrollerimpl_2eh_1217',['SPGlobalContextsControllerImpl.h',['../_s_p_global_contexts_controller_impl_8h.html',1,'']]],
  ['spglobalcontextscontrollerimpl_2em_1218',['SPGlobalContextsControllerImpl.m',['../_s_p_global_contexts_controller_impl_8m.html',1,'']]],
  ['spinstalltracker_2eh_1219',['SPInstallTracker.h',['../_s_p_install_tracker_8h.html',1,'']]],
  ['spinstalltracker_2em_1220',['SPInstallTracker.m',['../_s_p_install_tracker_8m.html',1,'']]],
  ['splogger_2eh_1221',['SPLogger.h',['../_s_p_logger_8h.html',1,'']]],
  ['splogger_2em_1222',['SPLogger.m',['../_s_p_logger_8m.html',1,'']]],
  ['sploggerdelegate_2eh_1223',['SPLoggerDelegate.h',['../include_2_s_p_logger_delegate_8h.html',1,'(Global Namespace)'],['../_internal_2_logger_2_s_p_logger_delegate_8h.html',1,'(Global Namespace)']]],
  ['spnetworkconfiguration_2eh_1224',['SPNetworkConfiguration.h',['../include_2_s_p_network_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_network_configuration_8h.html',1,'(Global Namespace)']]],
  ['spnetworkconfiguration_2em_1225',['SPNetworkConfiguration.m',['../_s_p_network_configuration_8m.html',1,'']]],
  ['spnetworkconnection_2eh_1226',['SPNetworkConnection.h',['../include_2_s_p_network_connection_8h.html',1,'(Global Namespace)'],['../_internal_2_network_connection_2_s_p_network_connection_8h.html',1,'(Global Namespace)']]],
  ['spnetworkcontroller_2eh_1227',['SPNetworkController.h',['../include_2_s_p_network_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_network_connection_2_s_p_network_controller_8h.html',1,'(Global Namespace)']]],
  ['spnetworkcontrollerimpl_2eh_1228',['SPNetworkControllerImpl.h',['../_s_p_network_controller_impl_8h.html',1,'']]],
  ['spnetworkcontrollerimpl_2em_1229',['SPNetworkControllerImpl.m',['../_s_p_network_controller_impl_8m.html',1,'']]],
  ['sppageview_2eh_1230',['SPPageView.h',['../include_2_s_p_page_view_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_page_view_8h.html',1,'(Global Namespace)']]],
  ['sppageview_2em_1231',['SPPageView.m',['../_s_p_page_view_8m.html',1,'']]],
  ['sppayload_2eh_1232',['SPPayload.h',['../include_2_s_p_payload_8h.html',1,'(Global Namespace)'],['../_internal_2_payload_2_s_p_payload_8h.html',1,'(Global Namespace)']]],
  ['sppayload_2em_1233',['SPPayload.m',['../_s_p_payload_8m.html',1,'']]],
  ['sppushnotification_2eh_1234',['SPPushNotification.h',['../include_2_s_p_push_notification_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_push_notification_8h.html',1,'(Global Namespace)']]],
  ['sppushnotification_2em_1235',['SPPushNotification.m',['../_s_p_push_notification_8m.html',1,'']]],
  ['sprequest_2eh_1236',['SPRequest.h',['../include_2_s_p_request_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_request_8h.html',1,'(Global Namespace)']]],
  ['sprequest_2em_1237',['SPRequest.m',['../_s_p_request_8m.html',1,'']]],
  ['sprequestcallback_2eh_1238',['SPRequestCallback.h',['../include_2_s_p_request_callback_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_request_callback_8h.html',1,'(Global Namespace)']]],
  ['sprequestresult_2eh_1239',['SPRequestResult.h',['../include_2_s_p_request_result_8h.html',1,'(Global Namespace)'],['../_internal_2_emitter_2_s_p_request_result_8h.html',1,'(Global Namespace)']]],
  ['sprequestresult_2em_1240',['SPRequestResult.m',['../_s_p_request_result_8m.html',1,'']]],
  ['spschemarule_2eh_1241',['SPSchemaRule.h',['../include_2_s_p_schema_rule_8h.html',1,'(Global Namespace)'],['../_internal_2_global_contexts_2_s_p_schema_rule_8h.html',1,'(Global Namespace)']]],
  ['spschemarule_2em_1242',['SPSchemaRule.m',['../_s_p_schema_rule_8m.html',1,'']]],
  ['spschemaruleset_2eh_1243',['SPSchemaRuleset.h',['../_internal_2_global_contexts_2_s_p_schema_ruleset_8h.html',1,'(Global Namespace)'],['../include_2_s_p_schema_ruleset_8h.html',1,'(Global Namespace)']]],
  ['spschemaruleset_2em_1244',['SPSchemaRuleset.m',['../_s_p_schema_ruleset_8m.html',1,'']]],
  ['spscreenstate_2eh_1245',['SPScreenState.h',['../_s_p_screen_state_8h.html',1,'']]],
  ['spscreenstate_2em_1246',['SPScreenState.m',['../_s_p_screen_state_8m.html',1,'']]],
  ['spscreenview_2eh_1247',['SPScreenView.h',['../include_2_s_p_screen_view_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_screen_view_8h.html',1,'(Global Namespace)']]],
  ['spscreenview_2em_1248',['SPScreenView.m',['../_s_p_screen_view_8m.html',1,'']]],
  ['spselfdescribing_2eh_1249',['SPSelfDescribing.h',['../include_2_s_p_self_describing_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_self_describing_8h.html',1,'(Global Namespace)']]],
  ['spselfdescribing_2em_1250',['SPSelfDescribing.m',['../_s_p_self_describing_8m.html',1,'']]],
  ['spselfdescribingjson_2eh_1251',['SPSelfDescribingJson.h',['../include_2_s_p_self_describing_json_8h.html',1,'(Global Namespace)'],['../_internal_2_payload_2_s_p_self_describing_json_8h.html',1,'(Global Namespace)']]],
  ['spselfdescribingjson_2em_1252',['SPSelfDescribingJson.m',['../_s_p_self_describing_json_8m.html',1,'']]],
  ['spserviceprovider_2eh_1253',['SPServiceProvider.h',['../_s_p_service_provider_8h.html',1,'']]],
  ['spserviceprovider_2em_1254',['SPServiceProvider.m',['../_s_p_service_provider_8m.html',1,'']]],
  ['spsession_2eh_1255',['SPSession.h',['../_s_p_session_8h.html',1,'']]],
  ['spsession_2em_1256',['SPSession.m',['../_s_p_session_8m.html',1,'']]],
  ['spsessionconfiguration_2eh_1257',['SPSessionConfiguration.h',['../include_2_s_p_session_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_session_configuration_8h.html',1,'(Global Namespace)']]],
  ['spsessionconfiguration_2em_1258',['SPSessionConfiguration.m',['../_s_p_session_configuration_8m.html',1,'']]],
  ['spsessioncontroller_2eh_1259',['SPSessionController.h',['../include_2_s_p_session_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_session_2_s_p_session_controller_8h.html',1,'(Global Namespace)']]],
  ['spsessioncontrollerimpl_2eh_1260',['SPSessionControllerImpl.h',['../_s_p_session_controller_impl_8h.html',1,'']]],
  ['spsessioncontrollerimpl_2em_1261',['SPSessionControllerImpl.m',['../_s_p_session_controller_impl_8m.html',1,'']]],
  ['spsnowplow_2eh_1262',['SPSnowplow.h',['../include_2_s_p_snowplow_8h.html',1,'(Global Namespace)'],['../_internal_2_s_p_snowplow_8h.html',1,'(Global Namespace)']]],
  ['spsnowplow_2em_1263',['SPSnowplow.m',['../_s_p_snowplow_8m.html',1,'']]],
  ['spsqliteeventstore_2eh_1264',['SPSQLiteEventStore.h',['../include_2_s_p_s_q_lite_event_store_8h.html',1,'(Global Namespace)'],['../_internal_2_storage_2_s_p_s_q_lite_event_store_8h.html',1,'(Global Namespace)']]],
  ['spsqliteeventstore_2em_1265',['SPSQLiteEventStore.m',['../_s_p_s_q_lite_event_store_8m.html',1,'']]],
  ['spstructured_2eh_1266',['SPStructured.h',['../include_2_s_p_structured_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_structured_8h.html',1,'(Global Namespace)']]],
  ['spstructured_2em_1267',['SPStructured.m',['../_s_p_structured_8m.html',1,'']]],
  ['spsubject_2eh_1268',['SPSubject.h',['../include_2_s_p_subject_8h.html',1,'(Global Namespace)'],['../_internal_2_subject_2_s_p_subject_8h.html',1,'(Global Namespace)']]],
  ['spsubject_2em_1269',['SPSubject.m',['../_s_p_subject_8m.html',1,'']]],
  ['spsubjectconfiguration_2eh_1270',['SPSubjectConfiguration.h',['../_internal_2_configurations_2_s_p_subject_configuration_8h.html',1,'(Global Namespace)'],['../include_2_s_p_subject_configuration_8h.html',1,'(Global Namespace)']]],
  ['spsubjectconfiguration_2em_1271',['SPSubjectConfiguration.m',['../_s_p_subject_configuration_8m.html',1,'']]],
  ['sptiming_2eh_1272',['SPTiming.h',['../include_2_s_p_timing_8h.html',1,'(Global Namespace)'],['../_internal_2_events_2_s_p_timing_8h.html',1,'(Global Namespace)']]],
  ['sptiming_2em_1273',['SPTiming.m',['../_s_p_timing_8m.html',1,'']]],
  ['sptracker_2eh_1274',['SPTracker.h',['../include_2_s_p_tracker_8h.html',1,'(Global Namespace)'],['../_internal_2_tracker_2_s_p_tracker_8h.html',1,'(Global Namespace)']]],
  ['sptracker_2em_1275',['SPTracker.m',['../_s_p_tracker_8m.html',1,'']]],
  ['sptrackerconfiguration_2eh_1276',['SPTrackerConfiguration.h',['../include_2_s_p_tracker_configuration_8h.html',1,'(Global Namespace)'],['../_internal_2_configurations_2_s_p_tracker_configuration_8h.html',1,'(Global Namespace)']]],
  ['sptrackerconfiguration_2em_1277',['SPTrackerConfiguration.m',['../_s_p_tracker_configuration_8m.html',1,'']]],
  ['sptrackerconstants_2eh_1278',['SPTrackerConstants.h',['../include_2_s_p_tracker_constants_8h.html',1,'(Global Namespace)'],['../_internal_2_s_p_tracker_constants_8h.html',1,'(Global Namespace)']]],
  ['sptrackerconstants_2em_1279',['SPTrackerConstants.m',['../_s_p_tracker_constants_8m.html',1,'']]],
  ['sptrackercontroller_2eh_1280',['SPTrackerController.h',['../include_2_s_p_tracker_controller_8h.html',1,'(Global Namespace)'],['../_internal_2_tracker_2_s_p_tracker_controller_8h.html',1,'(Global Namespace)']]],
  ['sptrackercontrollerimpl_2eh_1281',['SPTrackerControllerImpl.h',['../_s_p_tracker_controller_impl_8h.html',1,'']]],
  ['sptrackercontrollerimpl_2em_1282',['SPTrackerControllerImpl.m',['../_s_p_tracker_controller_impl_8m.html',1,'']]],
  ['sptrackererror_2eh_1283',['SPTrackerError.h',['../_s_p_tracker_error_8h.html',1,'']]],
  ['sptrackererror_2em_1284',['SPTrackerError.m',['../_s_p_tracker_error_8m.html',1,'']]],
  ['sptrackerevent_2eh_1285',['SPTrackerEvent.h',['../_s_p_tracker_event_8h.html',1,'']]],
  ['sptrackerevent_2em_1286',['SPTrackerEvent.m',['../_s_p_tracker_event_8m.html',1,'']]],
  ['sputilities_2eh_1287',['SPUtilities.h',['../include_2_s_p_utilities_8h.html',1,'(Global Namespace)'],['../_internal_2_utils_2_s_p_utilities_8h.html',1,'(Global Namespace)']]],
  ['sputilities_2em_1288',['SPUtilities.m',['../_s_p_utilities_8m.html',1,'']]],
  ['spweaktimertarget_2eh_1289',['SPWeakTimerTarget.h',['../_s_p_weak_timer_target_8h.html',1,'']]],
  ['spweaktimertarget_2em_1290',['SPWeakTimerTarget.m',['../_s_p_weak_timer_target_8m.html',1,'']]]
];
