# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnowplowSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '12.0'

  # Pods for SnowplowSwiftDemo

  pod 'SnowplowTracker', :path => '../'

  target 'SnowplowSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnowplowSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'SnowplowSwiftDemoWatch WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  platform :watchos, '2.0'

  # Pods for SnowplowSwiftDemo

  pod 'SnowplowTracker', :path => '../'
end
