# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnowplowSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '8.0'

  # Pods for SnowplowSwiftDemo

  pod 'SnowplowTracker', :path => '../'
  pod 'SwiftTryCatch'

  target 'SnowplowSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnowplowSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end
