platform :ios, '9.0'
#use_frameworks!

workspace 'SnowplowSwiftDemo.xcworkspace'

target 'SnowplowSwiftDemo' do
    pod 'FMDB', '~> 2.6.2', :modular_headers => true
    pod 'SnowplowTracker', :path=> '../../'
end

