platform :ios, '9.0'
use_frameworks!

workspace 'SnowplowSwiftDemo.xcworkspace'

target 'SnowplowSwiftDemo' do
    pod 'SnowplowTracker', :path=> '../../'
end

target 'SnowplowSwiftWatch Extension' do
    platform :watchos, '4.0' 
    pod 'SnowplowTracker', :path=> '../../'
  end

