name: Documentation

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1

      - name: Generate documentation
        run: |
          swift package --allow-writing-to-directory docs generate-documentation --target SnowplowTracker --disable-indexing --output-path docs --transform-for-static-hosting --hosting-base-path snowplow-ios-tracker

      - name: Redirect from the index page
        run: |
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url='https://snowplow.github.io/snowplow-ios-tracker/documentation/snowplowtracker/'" /></head><body></body></html>' > docs/index.html
    
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
